// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZa8JIJhjcKGxw4sVWlOnNGwass7uZbkA',
    appId: '1:106269880093:web:39e51f06ba3f8cbf1cbbf4',
    messagingSenderId: '106269880093',
    projectId: 'eventpix-2c431',
    authDomain: 'eventpix-2c431.firebaseapp.com',
    storageBucket: 'eventpix-2c431.firebasestorage.app',
    measurementId: 'G-MXXCBECGE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFeypX-YHO01ZoGw6ra86zH43uaLKeUCU',
    appId: '1:106269880093:android:59710474e181362a1cbbf4',
    messagingSenderId: '106269880093',
    projectId: 'eventpix-2c431',
    storageBucket: 'eventpix-2c431.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcfoUTG94his05ZT30ZhPr3pj9A-6LexQ',
    appId: '1:106269880093:ios:a5468e4b4f8bc80b1cbbf4',
    messagingSenderId: '106269880093',
    projectId: 'eventpix-2c431',
    storageBucket: 'eventpix-2c431.firebasestorage.app',
    iosBundleId: 'com.example.eventpix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcfoUTG94his05ZT30ZhPr3pj9A-6LexQ',
    appId: '1:106269880093:ios:a5468e4b4f8bc80b1cbbf4',
    messagingSenderId: '106269880093',
    projectId: 'eventpix-2c431',
    storageBucket: 'eventpix-2c431.firebasestorage.app',
    iosBundleId: 'com.example.eventpix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZa8JIJhjcKGxw4sVWlOnNGwass7uZbkA',
    appId: '1:106269880093:web:508564597715f4881cbbf4',
    messagingSenderId: '106269880093',
    projectId: 'eventpix-2c431',
    authDomain: 'eventpix-2c431.firebaseapp.com',
    storageBucket: 'eventpix-2c431.firebasestorage.app',
    measurementId: 'G-85GJKXT0JR',
  );
}
